batch_size: 64
buffer_size: 100000
learning_rate: 0.00005
eta_min: 0.000001
gamma: 0.99
epsilon_start: 1.0
epsilon_end: 0.1
epsilon_decay: 2000
target_update_freq: 1000
num_episodes: 5000
max_steps_per_episode: 200
eval_interval: 50
checkpoint_interval: 100
