PongNoFrameskip-v4:
  num_atoms: 51
  Vmin: -10
  Vmax: 10
  lr: 0.00025
  frame_stack: 4
  max_iters: 10000
  buffer_capacity: 100000

BreakoutNoFrameskip-v4:
  num_atoms: 51
  Vmin: -10
  Vmax: 10
  lr: 0.00025
  frame_stack: 4
  max_iters: 10000
  buffer_capacity: 100000

SeaquestNoFrameskip-v4:
  num_atoms: 51
  Vmin: -10
  Vmax: 10
  lr: 0.00025
  frame_stack: 4
  max_iters: 10000
  buffer_capacity: 100000
